# Generated by Django 2.1.7 on 2019-02-13 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("people", "0016_auto_20171206_1449"),
        ("classes", "0023_auto_20190131_1159"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation time"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last modification time"
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        help_text="Justification.  Include both sections here for a section change."
                    ),
                ),
                ("instructor_signed", models.DateField(blank=True, null=True)),
                ("dept_head_signed", models.DateField(blank=True, null=True)),
                (
                    "dept_head",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"flags__slug": "instructor"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="permissions_granted_as_head",
                        to="people.Person",
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"flags__slug": "instructor"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="permissions_granted_as_instructor",
                        to="people.Person",
                    ),
                ),
            ],
            options={"base_manager_name": "objects"},
        ),
        migrations.CreateModel(
            name="Reason",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation time"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last modification time"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A reason for the special permission", max_length=100
                    ),
                ),
            ],
            options={"ordering": ["name"], "base_manager_name": "objects"},
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation time"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last modification time"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("student_number", models.CharField(max_length=32)),
                ("email", models.EmailField(blank=True, max_length=254)),
            ],
            options={"base_manager_name": "objects"},
        ),
        migrations.AddField(
            model_name="permission",
            name="reasons",
            field=models.ManyToManyField(
                help_text="Select as many as apply", to="studentperms.Reason"
            ),
        ),
        migrations.AddField(
            model_name="permission",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="classes.Section"
            ),
        ),
        migrations.AddField(
            model_name="permission",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="studentperms.Student"
            ),
        ),
    ]
