# Generated by Django 2.1.7 on 2019-02-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("studentperms", "0001_initial")]

    operations = [
        migrations.AlterModelOptions(
            name="reason",
            options={"base_manager_name": "objects", "ordering": ["ordering", "name"]},
        ),
        migrations.AddField(
            model_name="reason",
            name="ordering",
            field=models.PositiveSmallIntegerField(
                default=50,
                help_text="Reasons are sorted by the ordering number first, then by name",
            ),
        ),
    ]
