# Generated by Django 2.1.7 on 2019-03-12 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("studentperms", "0003_auto_20190312_1350")]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="dept_head",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"flags__slug": "instructor"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="permissions_granted_as_head",
                to="people.Person",
                verbose_name="department head or designate",
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="dept_head_signed",
            field=models.DateField(
                blank=True,
                help_text="Dates are YYYY-MM-DD.",
                null=True,
                verbose_name="signed on",
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="instructor_signed",
            field=models.DateField(
                blank=True,
                help_text="Dates are YYYY-MM-DD.",
                null=True,
                verbose_name="signed on",
            ),
        ),
    ]
